name: Remove Background → MP4 nền đen (No Audio, Full Length)

on:
  workflow_dispatch:
    inputs:
      VIDEO_URL:
        description: "Tùy chọn: URL video để tải (YouTube/TikTok/Twitch...). Bỏ trống để dùng file trong repo."
        required: false
        default: ""
      INPUT_PATH:
        description: "Đường dẫn file có sẵn trong repo (nếu không dùng VIDEO_URL)"
        required: false
        default: "INPUT/input.mp4"
      FPS:
        description: "FPS xử lý (24/25/30)"
        required: false
        default: "30"
      MODEL:
        description: "Model (tuỳ chọn): u2net | u2netp | u2net_human_seg | isnet-general-use"
        required: false
        default: ""

jobs:
  remove_bg:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare folders
        run: |
          mkdir -p INPUT OUT .work

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Torch (CPU) + BackgroundRemover (+ yt-dlp nếu dùng URL)
        run: |
          python -m pip install --upgrade pip
          python -m pip install --index-url https://download.pytorch.org/whl/cpu torch torchvision torchaudio
          python -m pip install backgroundremover==0.3.4 yt-dlp

      - name: Cache Torch & Models
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/torch
            ~/.cache/backgroundremover
            ~/.u2net
          key: bgrem-${{ runner.os }}-${{ hashFiles('.github/workflows/remove_bg.yml') }}

      - name: Resolve input video (download or use repo file)
        id: resolve
        shell: bash
        run: |
          set -euo pipefail
          if [ -n "${{ inputs.VIDEO_URL }}" ]; then
            echo "[INFO] Downloading: ${{ inputs.VIDEO_URL }}"
            yt-dlp -o INPUT/input.mp4 "${{ inputs.VIDEO_URL }}"
            SRC="INPUT/input.mp4"
          else
            SRC="${{ inputs.INPUT_PATH }}"
            if [ ! -f "$SRC" ]; then
              echo "::error::Không tìm thấy file nguồn: $SRC. Hãy commit file vào repo hoặc cung cấp VIDEO_URL."
              exit 1
            fi
          fi
          echo "src=$SRC" >> "$GITHUB_OUTPUT"

      - name: Remove background → TEMP MOV (alpha, full length)
        shell: bash
        run: |
          set -euo pipefail
          SRC="${{ steps.resolve.outputs.src }}"
          FPS="${{ inputs.FPS }}"
          MODEL="${{ inputs.MODEL }}"
          if [ -n "$MODEL" ]; then M="-m $MODEL"; else M=""; fi
          echo "[INFO] backgroundremover -i \"$SRC\" -fr $FPS $M -tv -o .work/cutout_tmp.mov"
          backgroundremover -i "$SRC" -fr "$FPS" $M -tv -o .work/cutout_tmp.mov

      - name: Flatten to MP4 (BLACK BG, NO AUDIO)
        shell: bash
        run: |
          set -euo pipefail
          # Ghép foreground (alpha) lên nền ĐEN. Không xuất audio (-an).
          # scale2ref để nền khớp kích thước video foreground.
          ffmpeg -y -hide_banner -loglevel error \
            -f lavfi -i color=c=black:s=16x16:d=999999 \
            -i .work/cutout_tmp.mov \
            -filter_complex "[1:v]format=rgba[fg];[0:v][fg]scale2ref[bg][fg2];[bg][fg2]overlay=shortest=1" \
            -an -c:v libx264 -pix_fmt yuv420p OUT/out.mp4

      - name: Cleanup temp alpha
        shell: bash
        run: |
          rm -f .work/cutout_tmp.mov
          echo "[OK] out.mp4 ready (nền đen, không tiếng)."

      - name: List outputs
        run: ls -lh OUT/

      - name: Upload artifact (out.mp4 only)
        uses: actions/upload-artifact@v4
        with:
          name: remove-bg-out
          path: OUT/out.mp4
